# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_users',
            name='date_joined',
            field=models.CharField(max_length=50),
        ),
    ]
