# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
