# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20180416_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsForm',
        ),
    ]
