# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20180503_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles',
            name='exp_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
