# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20180503_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('role_id', models.CharField(max_length=100)),
                ('sub_date', models.CharField(max_length=100)),
                ('exp_date', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
