# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_delete_eventsform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
