# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_subscription_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_log',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Roles'),
        ),
        migrations.AlterField(
            model_name='subscription_log',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Front_Users'),
        ),
    ]
