# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_auto_20180507_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_log',
            name='tran_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user_roles',
            name='tran_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
