# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_auto_20180419_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsform',
            name='event_date',
            field=models.DateField(max_length=50),
        ),
    ]
