# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_auto_20180419_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='EventsForm',
        ),
    ]
