# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20180420_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
