# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Front_Users',
        ),
    ]
