# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_delete_front_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('date_joined', models.CharField(max_length=50)),
                ('redirect_to', models.CharField(max_length=50)),
            ],
        ),
    ]
