# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_front_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('expiry_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='member_user',
            name='membership_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Membership'),
        ),
        migrations.AddField(
            model_name='member_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Front_Users'),
        ),
    ]
