# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_auto_20180425_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_user',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member_user',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
