# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_auto_20180425_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_users',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
