# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_front_users_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='front_users',
            name='redirect_to',
        ),
    ]
