# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_auto_20180426_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_users',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
