# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_auto_20180427_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_users',
            name='role',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
