# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0023_front_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='front_users',
            name='role',
        ),
    ]
