# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0026_auto_20180501_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Front_Users')),
            ],
        ),
    ]
