# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0027_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='role_id',
        ),
        migrations.AddField(
            model_name='roles',
            name='id',
            field=models.AutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_roles',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Roles'),
        ),
    ]
