# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0028_auto_20180501_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_roles',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Roles'),
        ),
    ]
